[core]
core-sw-01 ansible_host=10.10.10.1 ansible_user=admin ansible_password=P@ssw0rd ansible_network_os=ios

[distribution]
dist-sw-f1 ansible_host=10.10.10.11 ansible_user=admin ansible_password=P@ssw0rd ansible_network_os=ios
dist-sw-f2 ansible_host=10.10.10.12 ansible_user=admin ansible_password=P@ssw0rd ansible_network_os=ios

[access]
access-lab-101 ansible_host=10.10.10.101 ansible_user=admin ansible_password=P@ssw0rd ansible_network_os=ios
access-lab-102 ansible_host=10.10.10.102 ansible_user=admin ansible_password=P@ssw0rd ansible_network_os=ios

[all:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=ios
ansible_become=yes
ansible_become_method=enable
ansible_become_password=P@ssw0rd